name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME_BACKEND: azure-crud-backend-app
  AZURE_WEBAPP_NAME_FRONTEND: azure-crud-frontend-app
  AZURE_WEBAPP_PACKAGE_PATH_BACKEND: 'backend'
  AZURE_WEBAPP_PACKAGE_PATH_FRONTEND: 'frontend'
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install dependencies
      run: |
        cd backend
        npm ci

    - name: Deploy to Azure Web App (Backend)
      id: deploy-to-webapp-backend
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_BACKEND }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH_BACKEND }}

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-and-deploy-backend
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies and build
      run: |
        cd frontend
        npm ci
        npm run build

    - name: Deploy to Azure Web App (Frontend)
      id: deploy-to-webapp-frontend
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_FRONTEND }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
        package: frontend/build
